### ISSUE TITLE
How do I turn on leyning in hebcal-fullcalendar.js ?

### ISSUE THREAD

**Issue by omert37** [hebcal/hebcal-leyning#1]
How do I turn on leyning in hebcal-fullcalendar.js 
in order to integrate and show the weekly Haftarah and Torah portion on the full calendar?

**Comment by mjradwin** [comment]
Here is an example of using both leyning and FullCalendar with Hebcal on
the client side.

https://gist.github.com/mjradwin/0ebb62ac6fa0abf23964#file-client-side-html

-- 
-- Sent from my mobile device

**Comment by omert37** [comment]
I was asking what do I need to do to display The **Haftarah Chapters & Verses** in hebcal-fullcalendar.js?
Is the option available via turning on a simple parameter (like candle lighting, Omer, Hebrew dates etc...):
https://www.hebcal.com/hebcal/?cfg=fc&v=1&i=on&maj=on&min=on&nx=on&mf=on&ss=on&mod=on&lg=s&s=on&m=50&c=on&o=on&d=on&geo=city&city=IL-Jerusalem

**Comment by mjradwin** [comment]
There isn't an option currently to do this. The example I sent is a way you
could implement this today.

We could consider adding the leyning summary information to the API so you
can use it in FullCalendar.io with some custom code like the following:

https://fullcalendar.io/docs/v4/eventRender

**Comment by mjradwin** [comment]
We released a change today to add a description to parsha hashavua events. You will still need to use the method described above to render a tooltip. You can replace newlines with HTML <br> tags in the tooltip

**Comment by omert37** [comment]
Could you please show me how to do it? (What lines of code, Where to put them)
Just as Parashat Hashavua appears, below that I want to add the weekly Torah portion (Book + Chapter + Verses).
I'm lost.

**Comment by mjradwin** [comment]
Here is a CodePen showing how to display tooltips with the Torah Portion & Haftarah

https://codepen.io/mjradwin/pen/XWjVrVE
