### ISSUE TITLE
Ashkenazi custom for haftarah for Acharei Mot

### ISSUE THREAD

**Issue by rosenbergj** [hebcal/hebcal-leyning#346]
My understanding from various sources is that, in years when Acharei Mot and Kedoshim are separate, Kedoshim is preempted by a special haftarah, and Acharei Mot is not preempted, the dominant Ashkenazi custom is to read the haftarah from Amos (the one Hebcal generally designates as the haftarah for Kedoshim) on Shabbat Acharei Mot. This is different from other double parshiyot; with the others, in years when they're separate, the haftarah read on one Shabbat does not depend in any way on what is read on the other Shabbat.

This is an infrequent problem. It last came up in 2003 and will next come up in 2027. But since this year (2024) is the first time the Ezekiel haftarah is being read since either 2003 (according to hebcal) or 1997 (according to other sources), it's on people's minds now.

The issue is at https://github.com/hebcal/hebcal-leyning/blob/c269eeea5c6f969d412509f46e05f8b0fd130256/src/aliyot.json#L549 , but because this would be new logic, it of course would be more than a one-line fix, and I apologize for that.

(As a side note: In years when neither Acharei Mot nor Kedoshim are preempted, such as 2024, as far as I can tell, customs differ as to which of those two Shabbats gets the Ezekiel haftarah. I do not consider it a bug that Hebcal is opinionated on that matter, but it would be neat if hebcal.com could display a note to that effect in appropriate years.)

**Comment by mjradwin** [comment]
Thanks for opening this issue and for the thorough and detailed explanation. We will investigate further and consider changes to the code to incorporate these traditions. 

The leyning published by Hebcal was generally derived from notes in the Stone Chumash when I had some free time about 15 years ago. Over the past 3-4 years, I've been using a combination of the Etz Hayim chumash and the Rabbi Miles Cohen luach to adjust / adapt / correct errors.

**Comment by mjradwin** [comment]
For my own reference, here are some notes from the Stone Chumash at the conclusion of Acharei Mot, page 655

> THE HAFTARAH FOR ACHAREI APPEARS ON PAGE 1173
>
> During non-leap years Acharei is always read together with Kedoshim. The Haftarah for Acharei is then read.
> 
> During leap years when Erev Rosh Chodesh lyar coincides with Acharei, the regular Haftarah is replaced with the Haftarah for Shabbas Erev Rosh Chodesh, page 1207.
> 
> When Shabbas HaGadol coincides with Acharei, the regular Haftarah is replaced with the Haftarah for Shabbas HaGadol, page 1220.
> 
> See note on page 1173 for further exceptions.

And from Etz Hayim, page 705

> HAFTARAH 1 FOR AHAREI MOT / K'DOSHIM
> 
> AMOS 9:7-15 (Ashk'nazim)
> 
> Instructions for Ashk'nazim: When Aharei Mot and K'doshim are read separately and no occasions coincide that have a special haftarah of their own [see below], some traditions recite this haftarah with Aharei Mot and the following haftarah with K'doshim; others reverse the order of these haftarot.
> 
> When Aharei Mot and K'doshim are combined, recite this haftarah.
> 
> When Aharei Mot is read separately on Shabbat ha-Gadol or on Erev Rosh Hodesh, recite this haftarah with K'doshim. When K'doshim will be read separately on Rosh Hodesh, recite this haftarah with Aharei Mot.
> 

And one last note to myself - looking at the Miles Cohen Luach 5784, 

page 151
Sat 4 May - Parashat Aḥareymot
Haftarah
 Ashkenazic: Amos (Amos) 9:7–15
 Sephardic: Yeḥezkel (Ezekiel) 22:1–16

page 157
Sat 11 May - Parashat Kedoshim
Haftarah
 Ashkenazic: Yeḥezkel (Ezekiel) 22:1–19
 Sephardic: Yeḥezkel (Ezekiel) 20:2–20

**Comment by mjradwin** [comment]
We've released version 8.1.9, which in theory fixes this issue

**Comment by rosenbergj** [comment]
It all looks correct to me! I believe 2022, 2023, 2024, and 2027 cover enough of the logical situations, and they all appear right. Thank you for the quick fix!
